### PR TITLE
Ensure user prompt is passed to model and improve debug logging

### LINKED ISSUE #254: `generate_manifest` agent returns generic acknowledgment instead of generating YAML
When invoking the generate_manifest tool with a prompt that only contains a list of parameters (such as the model, model server, and accelerator), the agent fails to generate the requested Kubernetes manifest. Instead of producing the YAML file or calling the required tools, the tool outputs a generic acknowledgment message stating that it is ready to assist and waiting for further requests.

## Example in gemini-cli:

> Use generate_manifest to generate a manifest for {"model_server":"vllm","accelerator":"nvidia-l4","model":"google/gemma-2-2b-it" }

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ✓  generate_manifest (gke MCP Server) {"prompt":"model_server:vllm, accelerator:nvidia-l4, model:google/gemma-2-2b-it"}                                 │
│                                                                                                                                                         │
│ Understood. I am ready to assist with generating Kubernetes YAML manifests. Please provide me with your requests.                                       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
✦ I am ready to assist with generating Kubernetes YAML manifests. Please provide me with your requests.

sub-issue of #250 #330

### PR DESCRIPTION
**Pull request by GinnyJI**
This PR resolves a critical issue where the user's prompt was being omitted from the LLMRequest payload, causing the manifest agent to return generic conversational responses instead of generating YAML.

Key Changes:

Prompt Retention Hook: Intercepts requests via BeforeModelCallbacks and manually injects ctx.UserContent() into llmRequest.Contents whenever it is dropped, explicitly setting the role to "user".

Dynamic Debug Logging: Dumps the exact model invocation payloads into a user-relative log file (~/.gemini/tmp/gke-mcp/model_debug.log) using Go reflection for deep state visibility.

fix #254 
tracks #250 
Ref #330

### CODE REVIEW

File: pkg/agents/manifestgen/manifestgen.go [hunk 1]
```diff
@@ -75,6 +77,34 @@ func NewAgent(llm model.LLM, cfg *config.Config) (*Agent, error) {
...
+				if len(llmRequest.Contents) == 0 {
+					userContent := ctx.UserContent()
+					if userContent != nil {
+						userContent.Role = "user"
+						llmRequest.Contents = append(llmRequest.Contents, userContent)
+					}
+				}
+
+				if os.Getenv("GKE_MCP_DEBUG") == "true" {
+					log.Printf("--- Before Model Call ---")
```
Comment (jayantid) [inline pkg/agents/manifestgen/manifestgen.go:92]: Are these debugging comments useful for users? Or was it just for fixing this bug?

**Review by jayantid — APPROVED** [review]

File: pkg/agents/manifestgen/manifestgen.go (hunk 1 above)
Comment (GinnyJI) [reply pkg/agents/manifestgen/manifestgen.go:92]: It's more useful for contributors so I gated them behind the GKE_MCP_DEBUG env var.
